export interface Product {
  id: number,
  pos?: string,
  product_number?: string,
  product_name?: string,
  product_image: string,
  modelId: number,
  categoryId: number,
  manufacturerId: number,
  product_description?: string,
  in_stock?: boolean,
  quantity?: number,
  price?: number,
  piston_group?: string,
  cylinder_block?: string,
  pressure_plate?: string,
  trunnion_medium?: string,
  shaft_splines_long?: string,
  shaft_key?: string,
  lens_small?: string,
  lens_medium?: string,
  lens_large?: string,
  notes?: string,
}

